-- CreateTable
CREATE TABLE "AdminSetting" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "deletePasswordHash" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
